spring:
  application.name: Wordgames
  datasource:
    url: jdbc:postgresql://localhost:5403/wordgames
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    url: "${spring.datasource.url}"
    user: "${spring.datasource.username}"
    password: "${spring.datasource.password}"
    placeholders:
      defaultMigratorRole: user
    initSqls:
      - SET ROLE "user"
